### ISSUE TITLE
Provide support for array constants (PHP 5.6+)

### ISSUE THREAD

**Issue by rrajkomar** [doctrine/annotations#108]
When using annotations with constant values (ie : SomeClass:CONSTANT), it is currently assumed that said constant will not be an array.

Starting PHP 5.6 constants can be arrays and while the doctrine parser does not fail reading the constant even if it is an array, it does not allow to access a single entry in the array without throwing the following error : 

`[Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_CURLY_BRACES, got '['`

It would be nice if we could use the array notation to access a specific element in the constant (i.e : SomeClass::CONSTANT[1])

**Comment by Ocramius** [comment]
Accessing a key is an expression, and expressions are not supported nor
allowed in annotations.

**Comment by rrajkomar** [comment]
I get that.
Although I still believe having some way to telle the annotation parser to use a specfific entry in the array could be very helpful
The syntax I put there as exemple was merely to expose my poiunt as clearly as possible, I'd be fine with any form of impelmentation as long as the expected behaviour is there :)

**Comment by Ocramius** [comment]
It still is an expression, and it will:

 * autoload the target class
 * cache an expression value into the annotation (not necessarily wanted, since we don't know if the constant will change, code-wise)

Closing as `won't fix`: we really *do not* want to go into evaluating any kind of expression.
