### ISSUE TITLE
Error with composer install --optimize-autoloader

### ISSUE THREAD

**Issue by chosroes** [doctrine/annotations#117]
As reported here : https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1637

When I try to clear/warm cache on production after composer install --optimize-autoloader I get this error :

Type error: Argument 1 passed to FOS\RestBundle\Request\ParamReader::getParamsFromAnnotationArray() must be of the type  
 array, null given, called in /var/www/infoflora/symfony/vendor/friendsofsymfony/rest-bundle/Request/ParamReader.php on  
 line 60

The problem come with annotations like that :

@QueryParam(map=true, name="sort", requirements=@Sort, allowBlank=false, default={Sort::DEFAULT_FIELD : Sort::DEFAULT_ORDER})

But everything is OK when I do not use the optimize option. Or when I use the full namespace in the annotation despite the use in the top of the class...

**Comment by mikeSimonson** [comment]
@chosroes Can you write a test case ?

**Comment by chosroes** [comment]
@mikeSimonson I don't know how exactly write this test, but the source of the error come from 1.3.1 with https://github.com/doctrine/annotations/pull/105

**Comment by mikeSimonson** [comment]
Here is a working prototype https://github.com/mikeSimonson/demo-annotation-with-const

Is there a difference with your code ?
