### ISSUE TITLE
Wrong parsing of DocBlocks with quotes in irrelevant text

### ISSUE THREAD

**Issue by julienfalque** [doctrine/annotations#126]
In the following docblock:
```
/**
 * @param mixed description with a single " character.
 *
 * @Marker
 *
 * @This is an irrelevant text with a single " character.
 */
```

`@Marker` is not correctly parsed because the lexer sees it as part of a string.

Is this expected? I wrote tests that cover this [here](https://github.com/julienfalque/annotations/tree/quotes) but I'm not sure how to fix this.

**Comment by Ocramius** [comment]
Could you please send the test case as a pull request?

Looks like a legitimate bug, and we should just stop looking for quotes
when we aren't in the context of an annotation.

**Comment by Ocramius** [comment]
Closing, as this was moved to #127
