### ISSUE TITLE
Doctrine\Annotations is unfriendly to extending

### ISSUE THREAD

**Issue by josefsabl** [doctrine/annotations#128]
I wanted to extend CachedReader with functionality described [here](http://stackoverflow.com/questions/27403516/find-all-entity-fields-with-a-specific-annotation) only to find that most internals are private although they should be protected. This way I can't use cache with my implementation. Why aren't they declared as protected? I have to work around this cumbersomely, duplicate lots of code etc. That is a shame.

**Comment by josefsabl** [comment]
Why? Without comment?

**Comment by mikeSimonson** [comment]
Read you request, you are literally just complaining that we not supporting your use case.

We don't have to make any of the project easy to extend. You don't seems to realise the added amount of maintenance work that it put on us.

You did not propose any PR or any solution.

You just came to complain that you had to write your code to support your use case.

**Comment by alcaeus** [comment]
@josefsabl The `CachedReader` is a decorator around a different `Reader` implementation. You shouldn't extend it to add your own stuff. You can either write your own decorator around a reader implementation or you write your own reader.

Given that StackOverflow link, I'm curious as to your use case. Neither the question, the answer or the comments suggest there should be something. This library is here to read in annotations and hand them to you for further processing. This further processing is up to you or a different library.

**Comment by josefsabl** [comment]
@mikeSimonson

Yes, I am complaining. I thought that raising issues is more or less about complaining (Does not mean I am mad at you or anything :-)

You are not obliged to do anything of course. Yet again, I thought that when you have this github thing up, you are interested in user feedback :-)

Well, solution is quite obvious, make properties protected instead of private.

As a programmer, I love writing code. I just hate to copy paste code and that is exactly what I was forced here.

I am sorry you thought I was flaming. I was not. I can explain my case further.

**Comment by alcaeus** [comment]
@josefsabl Extending a class is not something that should be done lightly - even more when that class is just a decorator to add a specific functionality (in this case, writing and reading information to/from a cache adapter). So, in the interest of improving a library, what would be the use case you were trying to build into the `CachedReader`?

**Comment by josefsabl** [comment]
@alcaeus Thanks for reaction (this is the reply to your first comment).

I am a bit confused though. Why I should not extend it? Should I copy paste it and add one function? Or maybe fork it?

Regarding the SO question. The most important part is the comments in the accepted answer. I thought I'd extend the Reader class with one method: getPropertiesWithAnnotation(\ReflectionClass $rc, $annotationName). Then I realized I want the result cached as well so I need to extend the CachedReader.

And voila, I cannot access the cache that is declared as private.

**Comment by alcaeus** [comment]
Take a look at the [reader interface](https://github.com/doctrine/annotations/blob/master/lib/Doctrine/Common/Annotations/Reader.php). Notice something? All methods dealing with class annotations take a `ReflectionClass` argument, those dealing with methods take a `ReflectionMethod` argument and those dealing with properties take a `ReflectionProperty` argument. At no point does the annotation reader deal with multiple classes, methods or properties at the same time. So, the use case clearly falls outside the scope of the library: it is designed to read the annotations for a single class, method or property and pass them on for further processing.

Take a look at the metadata drivers to see how they use this library: they take a reflection class object, loop over all properties and ask the annotation reader for the annotations on the property. Then, they deal with them.

So, in your project, if you wanted to have all properties of a class that specify a specific annotation, it's quite simple: create a class that takes any annotation reader and a `ReflectionClass` object and returns all those `ReflectionProperty` objects that match your criteria. That is a very short `array_map` that I admit I'm just too lazy to type into this comment box. With that solution, you've kept the "read annotations for a class" and "find all properties with a given annotation" domains separate without a lot of overhead.

**Comment by josefsabl** [comment]
Of course the solution is obvious and I have it down. I just wanted to encapsulated it in the reader class.

Everything you say is clear. I am just not sure with one point: What you suggest as antipattern is that the "Annotation reader class should always return annotations. It should not return properties". Correct?

Ok, I have a different opinion at the moment, but I guess it is just a matter of philosophy. I may try this approach to solve the problem and maybe it will change my views.

Anyways. Somebody someday may have another good reason to extend the class, so maybe the point of this issue still stands. I am however not that person :-)

Thanks for your time.

**Comment by alcaeus** [comment]
> Somebody someday may have another good reason to extend the class, so maybe the point of this issue still stands.

At that time, we'll re-evaluate the position and possibly change something on the class itself. There is no reason to allow extending a class when you're not even sure why somebody would want to extend it. You can always open up an API if required; closing it down is not easily possible.

**Comment by josefsabl** [comment]
Sure. Fair point. Thanks again.
