### ISSUE TITLE
DocParser does not interpret/validate multiple type docblocks correctly on annotation properties.

### ISSUE THREAD

**Issue by samdjstevens** [doctrine/annotations#129]
I have just ran into an issue on a Symfony app, where a property on a custom annotation that can either be a `string` or `null` causes an exception to be thrown upon parsing when used.

Example:

```
<?php
namespace AppBundle\Annotations;

use Doctrine\Common\Annotations\Annotation;

/**
 * @Annotation
 * @Target("PROPERTY")
 */
final class MyAnnotation 
{
    /**
     * @var string|null
     */
    public $theProperty;
}
```

When using this annotation and specifying a string value for `theProperty`,  an `AnnotationException` is thrown with the following message:

`[Type Error] Attribute "theProperty" of @MyAnnotation declared on property AppBundle\TestEntity::$test expects a(n) string|null, but got string.`

As far as I can see this is happening because it is not interpreting the pipe convention of declaring multiple types on the parameter.

**Comment by samdjstevens** [comment]
Hey @Ocramius - I'm happy to provide some tests/have a go at writing a PR to fix this, if you think that supporting this piped-multiple-types syntax is a good idea?

**Comment by Majkl578** [comment]
I'm afraid this may require a substantial work to support union types, since the parser only recognizes single types or array of single types...
https://github.com/doctrine/annotations/blob/54cacc9b81758b14e3ce750f205a393d52339e97/lib/Doctrine/Common/Annotations/DocParser.php#L547

**Comment by BenMorel** [comment]
Same problem here. Does anyone plan to work on this one?

**Comment by Ocramius** [comment]
Please sync up with @Majkl578: he's doing large chunks of work for Annotations 2.0

**Comment by leocavalcante** [comment]
Workaround for those using Psalm
```php
/**
 * @var string
 * @psalm-var string|null
 */
```

**Comment by alcaeus** [comment]
Closing here - with PHP 8 supporting union types, my recommendation would be to use attributes instead of annotations.
