### ISSUE TITLE
Fatal error after upgrade to 1.5.0

### ISSUE THREAD

**Issue by npetrovski** [doctrine/annotations#138]
After upgraded from 1.4.0 to 1.5.0 (I am using doctrine/or: 2.5.6 with all the default requires) the flowing error appeared:

**"Uncaught TypeError: Return value of Doctrine\Common\Annotations\AnnotationRegistry::registerFile() must be an instance of Doctrine\Common\Annotations\void, none returned in /library/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php:67"**

When explicitly downgraded back to 1.4.0 all is good. Please, have a look at the return type annotations.

Thanks.

**Comment by Ocramius** [comment]
@npetrovski `1.5.0` requires PHP 7.1. Make sure your development and production environments use the same version, and that you use locked composer dependencies.

Closing as `invalid`.

**Comment by bensquire** [comment]
@Ocramius This has caused problems for me when using the ODM. Previously doctrine/annotations wasn't an explicit dependency, so I've spent the best part of the last hour working out how to fix the issue; not sure what can be done but maybe some sort of notice to the community would be useful?

**Comment by Ocramius** [comment]
@bensquire see http://doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html

**Comment by Ocramius** [comment]
And also, this has nothing to do with doctrine itself: if you encountered issues during composer installation or runtime after an upgrade, that means that there is a massive problem in how you use composer. You can see https://github.com/doctrine/instantiator/issues/33 for an example of that.

**Comment by bensquire** [comment]
Thanks @Ocramius I think this stems from me previously using dev-master for composer dependencies (at the time I needed unreleased features). Correcting that has resolved the issue.

**Comment by npetrovski** [comment]
Just to confirm that @Ocramius was right about the PHP version, so to solve my problem with my environment running PHP7.0 I had to explicitly define the doctrine/orm deps:

instead of:

```
{
       "doctrine/orm": "2.5.6"
}
```
now I have:

```
{ 
        "doctrine/cache": "1.6.2",
        "doctrine/lexer": "1.0.1",
        "doctrine/inflector": "1.2.0",
        "doctrine/collections": "1.4.0",
        "doctrine/annotations": "1.4.0",
        "doctrine/common": "2.7.3",
        "doctrine/instantiator": "1.0.5",
        "doctrine/dbal": "2.5.13",
        "doctrine/orm": "2.5.6",
}
```

Not the best approach, but it works for me.

**Comment by Ocramius** [comment]
@nemekzg as explained in http://doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html, you should use the platform config.

**Comment by alcaeus** [comment]
> Not the best approach, but it works for me.

Allow me to just add that this isn't "not the best approach" but seriously the worst possible approach.

The good folks that wrote composer didn't implement the SAT solver for nothing. You can safely remove them (and change ORM to `^2.5`) once you've properly set up your environment and/or configured `config.platform` accordingly.
