### ISSUE TITLE
annotations 2.0: Rename library to doctrine/annotations2 ?

### ISSUE THREAD

**Issue by donquixote** [doctrine/annotations#144]
The following is an idea I am not so sure about myself.

In the PHP / Composer / Packagist ecosystem, we often see problems when popular packages get a new version out. The arguments from this kind of discussion also happened here, https://github.com/doctrine/annotations/pull/75.

The problem:
- A major version is often not fully backwards compatible to the previous version.
- It is not possible to install two major versions side by side on a project. It causes name clashes for PHP classes and namespaces, and it is not supported by the package manager.

So I have been wondering: Why not make the version number (beyond 1) part of the package name? E.g. if the 2.0 version would become `doctrine/annotations2`, it could be safely installed alongside the old version, and we/you could quite happily break things.

It seems like a solution to the problem, but I am not aware of any PHP libraries doing this. So I asked this on stackexchange, see [Major version number as part of package name / namespace?](https://softwareengineering.stackexchange.com/questions/356365/major-version-number-as-part-of-package-name-namespace).

One person, in [this answer](https://softwareengineering.stackexchange.com/a/356376/113434), mentioned that some projects actually do this, e.g. `python3`, `openjdk-9`, `libgtk2`.

So I am wondering why this is not more common in the PHP world, and whether `doctrine/annotations` should follow this idea.

**Comment by Majkl578** [comment]
> A major version is often not fully backwards compatible to the previous version.

> It is not possible to install two major versions side by side on a project. It causes name clashes for PHP classes and namespaces, and it is not supported by the package manager.

Why would you do such thing at first place? In vast majority of cases you do not want to install both versions (as it doesn't really even make sense, except some rare use cases), but upgrade to newer version.

This is perfectly ok and compliant with [semantic versioning](http://semver.org/) since it is a _major_ version.

> One person, in this answer, mentioned that some projects actually do this, e.g. python3, openjdk-9, libgtk2.

The reason these libraries use versioned packages is primarily to allow coinstallability, i.e. you can have both python 2 & 3 or gtk+2 & gtk+3.

**Comment by donquixote** [comment]
> Why would you do such thing at first place? In vast majority of cases you do not want to install both versions (as it doesn't really even make sense, except some rare use cases), but upgrade to newer version.

You would not do this, your package manager would. In case you depend on packages A and B, but A depends on C1 and is incompatible with C2, but B depends on C2.

**Comment by donquixote** [comment]
@stof Good points there.

> if you are a bit careful about what do in the new major version, it may be totally possible for a package to allow multiple major version of your package

So this compatibility should be a desirable goal, even when doing a new major version.

> renaming classes is the biggest BC break you can make (as it boils down to removing all classes and adding new ones).

So.. this would only be justified if you are already planning to rewrite everything anyway.

Otherwise, the best compromise might be to introduce new classes, instead of changing the API of existing classes.

**Comment by Majkl578** [comment]
Closing as per discussion. Master is now 2.0-dev.
