### ISSUE TITLE
How to Register CustomerAnnotation?

### ISSUE THREAD

**Issue by wuchuguang** [doctrine/annotations#148]
"doctrine/annotations": "^1.5"

![qq 20171023095609](https://user-images.githubusercontent.com/1677247/31869123-748bcdae-b7d8-11e7-9e5a-40ff13b7e197.png)

registerLoader deprecated

**Comment by Ocramius** [comment]
You can just do a `class_exists(MyAnnotation::class);`, for example: that will trigger autoloading.
