### ISSUE TITLE
how to ignore user define @xxxx?

### ISSUE THREAD

**Issue by wuchuguang** [doctrine/annotations#149]
"doctrine/annotations": "^1.5",
parser->setImports([
  'xxxx'
]);
but parse to extend it ,and not way to do like this .
can support like this,

AnnotationRegistry::ignoreAnnotations([
   'xxxx'
]);

**Comment by wuchuguang** [comment]
i use api doc https://github.com/apidoc/apidoc
has
@api 
@apiGroup
@api.xxxx

**Comment by wuchuguang** [comment]
I need ignore  @api, @apiParam xxx
thx.

**Comment by wuchuguang** [comment]
@mikeSimonson way closed my issue?

**Comment by wuchuguang** [comment]
AnnotationReader::addGlobalIgnoredName i Need this. thx

**Comment by mikeSimonson** [comment]
@wuchuguang Sorry I taught I closed this issue with a message about addGlobalIgnoredName.
