### ISSUE TITLE
orphan removal removes children, not orphans

### ISSUE THREAD

**Issue by stijn-at-work** [doctrine/annotations#168]
Upgrade from doctrine annotations 1.2.7 to 1.6.0 in our Symfony based application caused the removal of our EnvironmentAccesses records. Before, in version 1.2.7, the orphanRemoval=true annotation worked as expected and only removed orphans. After upgrade to version 1.6.0 the orphanRemoval annotation removed all children, not only orphans. 

**User parent**
```
/**
     * @ORM\OneToMany(targetEntity="Apptimize\AccountsBundle\Entity\EnvironmentAccess", mappedBy="user", cascade={"persist", "remove"}, orphanRemoval=true)
     * @Type("array<Apptimize\AccountsBundle\Entity\EnvironmentAccess>")
     * @var \Apptimize\AccountsBundle\Entity\EnvironmentAccess[]
     */
    private $environmentAccess;
```

**EnvironmentAccess child**
```
    /**
     * @ORM\ManyToOne(targetEntity="Apptimize\AccountsBundle\Entity\User", inversedBy="environmentAccess")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $user;
```

**Comment by Ocramius** [comment]
Did you intend to report this to doctrine/orm?

**Comment by stijn-apptimize** [comment]
not yet. i thought this was the right and most specific place.  the problem is solved when we add "doctrine/annotations": "1.2.7" to composer.json and run composer update. therefore we conclude that doctrine/annotations is the cause.

**Comment by Ocramius** [comment]
If doctrine/annotations changes the behaviour, I need you to dump and diff the `ClassMetadata` of the two entities with the two dependency sets. Also dump the diff of the output of `composer list --installed`.

**Comment by stijn-apptimize** [comment]
**composer show difference**
doctrine/annotations v1.2.7 > doctrine/annotations v1.6.0 
doctrine/orm v2.5.14 > doctrine/orm v2.6.0

**Comment by Ocramius** [comment]
Ah, so there is a difference in ORM version. I don't think this has to do
with annotations then.

**Comment by stijn-apptimize** [comment]
i will report the issue in doctrine/orm.

**Comment by Ocramius** [comment]
Moved to https://github.com/doctrine/doctrine2/issues/6999
