### ISSUE TITLE
IgnoreAnnotation not aplied to parent classes.

### ISSUE THREAD

**Issue by dvc** [doctrine/annotations#169]
doctrine/annotations  v1.6.0

```
/**
* @IgnoreAnnotation("bad")
**/
class A extends B {}

class B extends C {}

class C {
  /**
  * some comment @bad some other
  **/
   public $aaa;
}
```

Result:

```
In AnnotationException.php line 54:
                                                                               
  [Semantical Error] The annotation "@bad" in property C::$aaa was never imported. Did you mayb  
  e forget to add a "use" statement for this annotation?
```

**Comment by Ocramius** [comment]
All in the same file?

On 30 Jan 2018 11:23, "Chernosov Denis" <notifications@github.com> wrote:

doctrine/annotations v1.6.0

/**
* @IgnoreAnnotation("bad")
**/
class A extends B {
}

class B extends C {}

class C{

/**
* some comment @bad some other
**/
 public $aaa;
}

Result:

In AnnotationException.php line 54:

  [Semantical Error] The annotation "@bad" in property C::$aaa was
never imported. Did you mayb
  e forget to add a "use" statement for this annotation?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/doctrine/annotations/issues/169>, or mute the thread

**Comment by dvc** [comment]
No, in different files. It`s only for example.


I have class:

```
namespace App\Entity;
...

use unreal4u\TelegramAPI\Telegram\Types\ReplyKeyboardMarkup;

class TelegramReplyKeyboardMarkup extends ReplyKeyboardMarkup
...
```
which extends another class (see https://github.com/unreal4u/telegram-api/blob/master/src/Telegram/Types/ReplyKeyboardMarkup.php#L19 )

```
namespace unreal4u\TelegramAPI\Telegram\Types;
use unreal4u\TelegramAPI\Abstracts\KeyboardMethods;
...
class ReplyKeyboardMarkup extends KeyboardMethods
...
```

Real problem was with line: https://github.com/unreal4u/telegram-api/blob/master/src/Abstracts/KeyboardMethods.php#L11


When i tried to set \@IgnoreAnnotation("mentioned") in my App\Entity\TelegramReplyKeyboardMarkup

it has no effect.

And i have no idea, how to configure it globally. 

Only one workaround: addCompilePass (thanks that addGlobalIgnoredName is static method). See also my comment: https://github.com/symfony/symfony/issues/17000#issuecomment-361537177

IMHO:
1) global configure options required
2) IgnoreAnnotation should acts in deep of class hierachy. May be configurable.
3) May be ignore vendors/* by default? Or search only in src/ by default. It is also better for performance.

**Comment by Ocramius** [comment]
`@ignoreannotation("mentioned")` does not exist afaik. 

Ignoring annotations is documented in http://docs.doctrine-project.org/projects/doctrine-common/en/latest/reference/annotations.html

Closing as `invalid`

**Comment by dvc** [comment]
Hmm...

https://github.com/doctrine/annotations/blob/master/lib/Doctrine/Common/Annotations/Annotation/IgnoreAnnotation.php

**Comment by Ocramius** [comment]
It will only skip annotations when retrieving them, but it will still parse them: https://github.com/doctrine/annotations/blob/fe71864318b4912198a317783392c639221ec2fd/lib/Doctrine/Common/Annotations/AnnotationReader.php#L391-L397

**Comment by shehi** [comment]
@Ocramius , this problem is ever existing. Why was this issue closed, even though the sample provided by Author is valid and repeatable?
