### ISSUE TITLE
Need configure for blacklisting annotations

### ISSUE THREAD

**Issue by dvc** [doctrine/annotations#181]
Mirror of https://github.com/symfony/symfony/issues/26005

Annotations is fragile functionality some times. See https://github.com/symfony/symfony/issues/17000#issuecomment-361537177

My workaround works because AnnotationReader::addGlobalIgnoredName is static method.

But i's dirty hack, imho.

Better to have configutation ability for blacklisting annotations:

1) by path (ignore vendors by default?)
2) by namespace
3) by annotation name

**Comment by Ocramius** [comment]
Disagree here: more configuration, more mistakes done by users.

Annotations are globally defined symbols represented as classes decorated with `@Annotation`: you either have those classes defined or you don't.

Excluding an annotation simply means you will skip looking it up in the registered classes, and that's more than sufficient for the grand majority of use-cases.

What we could do in future is preventing usage of non-qualified annotations. Specifically, if an annotation isn't imported, it will be skipped  that's a better approach IMO.

**Comment by lcobucci** [comment]
> What we could do in future is preventing usage of non-qualified annotations. Specifically, if an annotation isn't imported, it will be skipped that's a better approach IMO.

@Ocramius I concur. Might be good to mention that we should expect this for annotations v2, correct?
