### ISSUE TITLE
AnnotationRegistry, everything is deprecated

### ISSUE THREAD

**Issue by panosru** [doctrine/annotations#182]
Hello, I'm a bit confused, inside `Doctrine\Common\Annotations\AnnotationRegistry` all methods are deprecated...

Currently I'm using the following:

```php
AnnotationRegistry::registerUniqueLoader('class_exists');
```

Should I continue using this or any other deprecated method like `registerFile`, `registerAutoloadNamespace`, `registerAutoloadNamespaces` and `registerLoader` or there is another way?

**Comment by Majkl578** [comment]
Please read the deprecation comment for `registerLoader()` method:
```
* @deprecated this method is deprecated and will be removed in doctrine/annotations 2.0
*             autoloading should be deferred to the globally registered autoloader by then. For now,
*             use @example AnnotationRegistry::registerLoader('class_exists')
```

**Comment by panosru** [comment]
So in other words, for time being, there isn't any other way to register autoloader right?

I mean, `AnnotationRegistry::registerLoader('class_exists')` is also deprecated method.

The reason I use `registerUniqueLoader` instead of `registerLoader` is because of #162

**Comment by Ocramius** [comment]
The idea is that at some point there won't be an `AnnotationRegistry` at all.

**Comment by stof** [comment]
@Ocramius should doctrine/annotations register `class_exists` automatically in the AnnotationRegistry ? For now, it is still mandatory to use the AnnotationRegistry layer, so deprecating it does not make much sense.

**Comment by Ocramius** [comment]
@stof it should just use `class_exists()` internally. @KingCrunch worked on this in #61.

**Comment by panosru** [comment]
@Ocramius, any idea when Annotations 2.0 will be live?

**Comment by Ocramius** [comment]
No idea, sorry - I'm barely getting to answer half the issues I get to read, which is half of the issues I receive.

**Comment by Majkl578** [comment]
Please see #205 which addresses removal of AnnotationRegistry. :blush:
