### ISSUE TITLE
Add a default namespace to load annotation classes from.

### ISSUE THREAD

**Issue by panosru** [doctrine/annotations#183]
I would love to be able to set a *default* namespace which would be used in order for the annotation classes to be loaded.

for instance instead of these ways:

Way 1:

```php
/**
 * @Path\To\Fully\Qualified\Class\Name\Foo(bar="bar")
 */
final class DubbyClass
{
}
```

Way 2:
```php
use Path\To\Fully\Qualified\Class\Name\Foo;

/**
 * @Foo(bar="bar")
 */
final class DubbyClass
{
}
```

To be able to have this:
```php
/**
 * @Foo(bar="bar")
 */
final class DubbyClass
{
}
```

There are plenty of reasons why I want to archive that:

- PhpStorm complains: `import 'Path\To\Fully\Qualified\Class\Name\Foo' is never used` as Is used only inside the doc block
- Typing less code

I tried the following:

```php
$docParser = new DocParser();
$docParser->setImports(['Path\To\Fully\Qualified\Class\Name']);

$this->reader = new IndexedReader(new CachedReader(
    new AnnotationReader($docParser),
    new ApcuCache(),
    true
));
```

but doesn't seem to work.

**Comment by malarzm** [comment]
> PhpStorm complains: import 'Path\To\Fully\Qualified\Class\Name\Foo' is never used as Is used only inside the doc block

IIRC it's not complaining if you have "Annotations" plugin installed :)

**Comment by alcaeus** [comment]
> IIRC it's not complaining if you have "Annotations" plugin installed :)

Correct. The suggestion of a “default” namespace is also an ugly workaround to a tooling problem in your case: importing the class or using the FQCN is the correct thing to do.

**Comment by panosru** [comment]
@malarzm Yup with the "Annotations" plugin is not complaining ;)

Thanks!
