### ISSUE TITLE
Annotation Parser does not replace namespace aliases

### ISSUE THREAD

**Issue by MelzerC** [doctrine/annotations#188]
Hey there!

I just setup a new phalcon project and want to use doctrine as ORM. Setup was pretty easy, up to the point of defining the model. 

To my setup: I'm using `doctrine/annotations` version 1.6

I defined an alias for the `Mapping` namespace (`use Doctrine\ORM\Mapping as ORM;`) as usual and defined the Model. Using the model results in an `Doctrine\ORM\Mapping\MappingException::classIsNotAValidEntityOrMappedSuperClass` exception.

After tracing down the issue, I found that the `DocParser::Annotation()` method is checking for an alias and found the correct one (`$alias` is set to `ORM` as expected) - line 695. The actual error occurs on line 701. `$namespace` is set to `Doctrine\ORM\Mapping` and `$name` is set to my alias, so `ORM\Entity`. That means, line 701 is checking for a class with a FQCN of `Doctrine\ORM\Mapping\ORM\Entity`. The alias should be stripped of the name, so the correct namespace could be checked.

I would be up for providing a fix for it, or if you need any further information - just let me know

Best
Chris

**Comment by Ocramius** [comment]
@MelzerC can you maybe show your bootstrap script?

**Comment by Ocramius** [comment]
https://github.com/doctrine/doctrine2/blob/87ee409783a4a322b5597ebaae558661404055a7/lib/Doctrine/ORM/Tools/Setup.php#L58-L75

Notice `$useSimpleAnnotationReader` ;-)
