### ISSUE TITLE
Share a simple demo

### ISSUE THREAD

**Issue by hunteryun** [doctrine/annotations#212]
Hi All

I'm a newer.  I'm looking for a annotations solution just like Drupal 8 Plugin system to integrate into my framework, then  I found this great package,  but read the official documents is hard. so I create this simple demo, I think this demo will help more newer like me. 

[demo.zip](https://github.com/doctrine/annotations/files/2135277/demo.zip)

**Comment by Ocramius** [comment]
Hello!

Could you please suggest an improvement to the existing documentation instead?

Closing here, as we can't do much with a zip 😅
