### ISSUE TITLE
Create index for table using column camelCase name broken

### ISSUE THREAD

**Issue by uginroot** [doctrine/annotations#214]
**My article entity:**
```php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 * @ORM\Table(indexes={
 *     @ORM\Index(name="isRemove", columns={"isRemove"}),
 * })
 */
class Article
{
    
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isRemove = false;

    // .....
}
```

I run the command to create a migration and get an error:
```
~: php bin/console make:migration

In SchemaException.php line 89:

  There is no column with name 'isRemove' on table 'article'.
```

If I change **isRemove** to **is_remove**, then everything starts working.

**Comment by malarzm** [comment]
This is not annotations issue but rather ORM. But to answer your problem: Doctrine by default uses [an underscore naming strategy](https://www.doctrine-project.org/projects/doctrine-orm/en/latest/reference/namingstrategy.html#underscore-naming-strategy) which means camel case named properties are changed to underscore ones in database (so your `isRemove` property is mapped to `is_remove` column). `@ORM\Index` operates on columns and as such requires you to feed it with list of column names.
