### ISSUE TITLE
Use PHPBench for performance testing

### ISSUE THREAD

**Issue by Majkl578** [doctrine/annotations#231]
Right now there is PerformanceTest that uses `microtime()`. In order to benchmark changes between 1.x and 2.0 something more sophisticated would be better - we use [PhpBench](https://github.com/phpbench/phpbench) in other projects.
This should be done for last 1.x release.

**Comment by Ocramius** [comment]
Full ack for @phpbench here: being able to compare profiles through its tooling would be very valuable, also for the @hoaproject folks.

**Comment by Majkl578** [comment]
This was done in #248.
