### ISSUE TITLE
Invalid syntax in DocLexer::nextTokenIsAdjacent

### ISSUE THREAD

**Issue by Deele** [doctrine/annotations#272]
in the [DocLexer](https://github.com/doctrine/annotations/blob/master/lib/Doctrine/Annotations/DocLexer.php#L68) there is a strange part where you have

```php
    /**
     * Whether the next token starts immediately, or if there were
     * non-captured symbols before that
     */
    public function nextTokenIsAdjacent() : bool
    {
        return $this->token === null
            || ($this->lookahead !== null
                && ($this->lookahead['position'] - $this->token['position']) === strlen($this->token['value']));
    }
```

What does ` : bool` do?

Cause I can't launch my app anymore with PHP 7.1 - `PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocLexer.php on line 85`

**Comment by Ocramius** [comment]
`: bool` is a return type declaration. Are you sure that you are running with PHP 7.1?

**Comment by SenseException** [comment]
@Deele Did you fixed the issue on your side? In case it is working for you now, please close this issue.
