### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by garak** [doctrine/annotations#273]
This stopped working on php 7.4, for example on [DocParser class](https://github.com/doctrine/annotations/blob/master/lib/Doctrine/Annotations/DocParser.php#L983) 
See https://twitter.com/nikita_ppv/status/1148931277216800769 for a reference

**Comment by Ocramius** [comment]
Ref: https://github.com/doctrine/annotations/blob/793b91ac63464dff1fa1e949f20214b7eecf6472/lib/Doctrine/Annotations/DocParser.php#L983

**Comment by rbairwell** [comment]
If it helps, the following seems to fix the problem:
`while ($this->lexer->lookahead!==null && $this->lexer->lookahead['position'] === ($this->lexer->token['position'] + strlen($this->lexer->token['value']))`

**Comment by Tobion** [comment]
Symfony also has alot of failures in php 7.4 due to this, ref. https://github.com/symfony/symfony/issues/32844

**Comment by davidbyoung** [comment]
Will the fix be merged into `master` in the near future?  I'm testing 2.0 on PHP 7.4-beta4, and am blocked.  Thanks!

**Comment by glensc** [comment]
RFC that implemented the breakage: https://wiki.php.net/rfc/notice-for-non-valid-array-container

**Comment by SuperlativeEntity** [comment]
Does this still seem to be broken?

ErrorException  : Trying to access array offset on value of type null
vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php:995

`while ($this->lexer->lookahead['position'] === ($this->lexer->token['position'] + strlen($this->lexer->token['value']))`

**Comment by alcaeus** [comment]
@SuperlativeEntity what version are you running? This has been fixed in 1.7.0.

**Comment by SuperlativeEntity** [comment]
Okay, my mistake, I have the wrong version. Thanks for your time.

**Comment by javiyt** [comment]
I'm using version 1.10.2 and its failing in other line:
```
[ErrorException]
 Trying to access array offset on value of type null
in /code/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php:1047
```

**Comment by SuperlativeEntity** [comment]
@javiyt Did you resolve the issue?

**Comment by javiyt** [comment]
No

**Comment by SuperlativeEntity** [comment]
Might be easier to just log a separate issue.

**Comment by grrenier** [comment]
> 
> 
> Does this still seem to be broken?
> 
> ErrorException : Trying to access array offset on value of type null
> vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php:995
> 
> `while ($this->lexer->lookahead['position'] === ($this->lexer->token['position'] + strlen($this->lexer->token['value']))`

This fixed the issue in my case: 

`while (isset($this->lexer->lookahead['position']) && $this->lexer->lookahead['position'] === ($this->lexer->token['position'] + strlen($this->lexer->token['value']))`

**Comment by darius-v** [comment]
> > Does this still seem to be broken?
> > ErrorException : Trying to access array offset on value of type null
> > vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php:995
> > `while ($this->lexer->lookahead['position'] === ($this->lexer->token['position'] + strlen($this->lexer->token['value']))`
> 
> This fixed the issue in my case:
> 
> `while (isset($this->lexer->lookahead['position']) && $this->lexer->lookahead['position'] === ($this->lexer->token['position'] + strlen($this->lexer->token['value']))`

for me this does not fix issue. I then get

[Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_NAMESPACE_SEPARATOR, got '(' at position 56 in class Vop\WebsiteBundle\Entity\SitewideNote.

**Comment by SuperlativeEntity** [comment]
We can't just edit the vendor files, it needs to be fixed in the package.

**Comment by Ocramius** [comment]
Hey folks: posting here won't help.

Please raise a new issue with **associated failing test case**, so it can be solved there.

**Comment by wiistriker** [comment]
still error on php 7.4

**Comment by ma-gu-16** [comment]
Confirm, still error on PHP 7.4 and current symfony flex   doctrine/orm v 2.7.5

**Comment by thewasta** [comment]
Anyone hava a solution?
I'm following this guide [AKENEO DOCS](https://docs.akeneo.com/1.5/developer_guide/installation/installation_archive.html) and when I run `php app/console cache:clear --env=prod` got the error 

```
Clearing the cache for the prod environment with debug false
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /root/pim-community-standard/vendor/symfony/monolog-bundle/DependencyInjection/Configuration.php on line 594
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /root/pim-community-standard/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2635
PHP Notice:  Trying to access array offset on value of type null in /root/pim-community-standard/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php on line 967
PHP Notice:  Trying to access array offset on value of type null in /root/pim-community-standard/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php on line 967
PHP Notice:  Trying to access array offset on value of type null in /root/pim-community-standard/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php on line 967
PHP Notice:  Trying to access array offset on value of type null in /root/pim-community-standard/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php on line 967
PHP Notice:  Trying to access array offset on value of type null in /root/pim-community-standard/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php on line 967
PHP Notice:  Trying to access array offset on value of type null in /root/pim-community-standard/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php on line 967
PHP Notice:  Trying to access array offset on value of type null in /root/pim-community-standard/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php on line 967
PHP Notice:  Trying to access array offset on value of type null in /root/pim-community-standard/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php on line 967
PHP Notice:  Trying to access array offset on value of type null in /root/pim-community-standard/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php on line 967
PHP Notice:  Trying to access array offset on value of type null in /root/pim-community-standard/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php on line 967
PHP Notice:  Trying to access array offset on value of type null in /root/pim-community-standard/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php on line 967
PHP Fatal error:  Declaration of Pim\Bundle\CatalogBundle\Doctrine\ORM\Repository\LocaleRepository::findBy(array $criteria, array $orderBy = Array, $limit = NULL, $offset = NULL) must be compatible with Doctrine\ORM\EntityRepository::findBy(array $criteria, ?array $orderBy = NULL, $limit = NULL, $offset = NULL) in /root/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/LocaleRepository.php on line 23
[2021-06-15 16:00:07] php.CRITICAL: Fatal Compile Error: Declaration of Pim\Bundle\CatalogBundle\Doctrine\ORM\Repository\LocaleRepository::findBy(array $criteria, array $orderBy = Array, $limit = NULL, $offset = NULL) must be compatible with Doctrine\ORM\EntityRepository::findBy(array $criteria, ?array $orderBy = NULL, $limit = NULL, $offset = NULL) {"type":64,"file":"/root/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/LocaleRepository.php","line":23,"level":6143,"stack":[]} []


                                                                                                                                                                                                                  
  [Symfony\Component\Debug\Exception\FatalErrorException]                                                                                                                                                         
  Compile Error: Declaration of Pim\Bundle\CatalogBundle\Doctrine\ORM\Repository\LocaleRepository::findBy(array $criteria, array $orderBy = Array, $limit = NULL, $offset = NULL) must be compatible with Doctri  
  ne\ORM\EntityRepository::findBy(array $criteria, ?array $orderBy = NULL, $limit = NULL, $offset = NULL)                                                                                                         
                                                                                                                                                                                                                  


cache:clear [--no-warmup] [--no-optional-warmers]

```

Current PHP version is 7.4, should I downgrade to 7.3 or upgrade to 8?

**Comment by Ocramius** [comment]
@thewasta please report it to `akeneo/pim-community-dev` - it has nothing to do with `doctrine/annotations`.
