### ISSUE TITLE
Remove PHP 7.4 from `allow_failures`

### ISSUE THREAD

**Issue by carusogabriel** [doctrine/annotations#285]
PHP 7.4 will be released [soon](https://wiki.php.net/todo/php74) and we need to ensure that `Doctrine` is compatible with it.

All we need to do is to remove these following lines

https://github.com/doctrine/annotations/blob/793b91ac63464dff1fa1e949f20214b7eecf6472/.travis.yml#L45-L46

 and verify that everything is working.

This is a very good issue for those who want to participate in https://hacktoberfest.digitalocean.com.

**Comment by alcaeus** [comment]
Compatibility with PHP 7.4 was introduced in 1.7.0, but this wasn't merged down to master because of issues with other PRs that haven't been backported to 1.7 in time.

I've got some time set aside to fix this later today and will check how to credit @sunspikes for their contribution here.

**Comment by alcaeus** [comment]
Fixed by merging up 1.8 into master. #286 was repurposed to fix travis-ci failures in the build.
