### ISSUE TITLE
AnnotationRegistry... ARE YOU SERIOS ?

### ISSUE THREAD

**Issue by zorn-v** [doctrine/annotations#292]
Yes, I know of impossible "annotation 2.0" (good progress since 2016) by this moment. But... I need to do `AnnotationRegistry::registerLoader(function ($class) {return \class_exists($class);});` in laravel project for example. Yep, then I should it remove because AnnotationRegistry will dissapear 

What reason of that ugly registry now ?
You are scare "2.0" magic ? Just do your Napoleon plans in "10.0"

**Comment by zorn-v** [comment]
PS. My atom just become crazy with php plugin and this project opened )

**Comment by Ocramius** [comment]
Closing: issue format not useful.

**Comment by greg0ire** [comment]
Is "Napolean plans" a russian expression? Je me sens attaqué.

**Comment by zorn-v** [comment]
> Is "Napolean plans" a russian expression? 
Yep. Something like great plans but not possible )

**Comment by zorn-v** [comment]
> Closing: issue format not useful.

This was a question by the way )
