### ISSUE TITLE
[performance] CacheReader::isCacheFresh cause too much call to filemtime

### ISSUE THREAD

**Issue by bastnic** [doctrine/annotations#300]
Context: big project, lof of entities that use annotations and a lot of traits.

The current implementation does something like this

```
foreach $entityClasses as $classes

	getClassAnnotation => x90
		fetchFromCache
			isCacheFresh
				filemtime for the $class, is parents and traits (easily 5 or 6 files)
	getMethodAnnotations
		foreach properties => 803
			fetchFromCache
				isCacheFresh
					filemtime for the $class, is parents and traits (easily 5 or 6 files)
	getPropertyAnnotations
		foreach properties => x1076
			fetchFromCache
				isCacheFresh
					filemtime for the $class, is parents and traits (easily 5 or 6 files)
```

For only 96 files, I'm calling 10951 filemtime.

![image](https://user-images.githubusercontent.com/84887/71354448-47dc1700-257c-11ea-836a-cfb664547cb8.png)

With a simple local cache on `getLastModification` with `$filename` as key (and we also can add on traits, but the cardinality is alreadly low enough), performance are up again \o/.

```php
    /**
     * Returns the time the class was last modified, testing traits and parents
     isCacheFresh*
     * @param ReflectionClass $class
     * @return int
     */
    private function getLastModification(ReflectionClass $class)
    {
        $filename = $class->getFileName();
		$cacheKey = '[T]' . $filename;
        
        if (isset($this->loadedAnnotations[$cacheKey])) {
            return $this->loadedAnnotations[$cacheKey];
        }
        $parent   = $class->getParentClass();

        return $this->loadedAnnotations[$cacheKey] = max(array_merge(
            [$filename ? filemtime($filename) : 0],
            array_map([$this, 'getTraitLastModificationTime'], $class->getTraits()),
            array_map([$this, 'getLastModification'], $class->getInterfaces()),
            $parent ? [$this->getLastModification($parent)] : []
        ));
    }

```

![image](https://user-images.githubusercontent.com/84887/71354547-92f62a00-257c-11ea-897b-d328cd4d1e92.png)

![image](https://user-images.githubusercontent.com/84887/71354624-d18be480-257c-11ea-947b-67cf888acf21.png)

**Comment by Ocramius** [comment]
> With a simple local cache 

Careful: this assumes immutable FS, which is a big assumption in generic libraries.

**Comment by bastnic** [comment]
@Ocramius Not sure what you mean, but I'm just talking of a class array that live for the live of the request. It should be reset at the next request. 

I had troubles with that, but in fact there is already a cache for the value of each (Property|Method|Class)Annotation, so a similar cache at filemtime level should not break anything.

**Comment by bastnic** [comment]
Changed the implementation to use a different key in the already instancied / cleared property loadedAnnotations
