### ISSUE TITLE
How to deal with 3rd-party annotations as a library author?

### ISSUE THREAD

**Issue by mnapoli** [doctrine/annotations#308]
Apologies if that has already been discussed.

In the [php-enum](https://github.com/myclabs/php-enum) project we recently added Psalm annotations (https://github.com/myclabs/php-enum/pull/111). For example `@template T` for generics support.

Users are now reporting Doctrine Annotations errors:

```
The annotation "@template" in class MyCLabs\Enum\Enum was never imported. Did you maybe forget to add a "use" statement for this annotation?
```

(see https://github.com/myclabs/php-enum/issues/113)

Years ago I had that problem *as a user*, and manually disabled that error in Doctrine Annotation via configuration.

However, **as a library author**, what can I do to avoid impacting users? Right now I feel like I am breaking users applications by simply adding a comment, it doesn't feel good :/

**Comment by andrew-demb** [comment]
As I can see, generic annotations added in https://github.com/doctrine/annotations/pull/298 and not released yet (target version is `1.9`)

**Comment by andrew-demb** [comment]
@mnapoli I think for now (until `1.9.0` is not released) you can use vendor-prefixed annotations (`psalm-template / phpstan-template`) which are automatically ignored since `1.6.1` (https://github.com/doctrine/annotations/releases/tag/v1.6.1)

**Comment by mnapoli** [comment]
@andrew-demb thanks, maybe we should indeed switch to the `psalm-` prefixed annotations.

**Comment by jtheuerkauf** [comment]
i see this question is several years old, so maybe someone can point me in the direction of something more current/relevant.

i think i recently came across this type of problem in another library, [reported here](https://github.com/spiral-packages/database-seeder/issues/40): An unsupported `@note` annotation was introduced in a build, but wasn't added to be explicitly ignored by this library.

They fixed that issue internally by adding `'note'` and a few others to be ignored. However, this seems like unnecessary overhead burden placed on library maintainers.

Comments shouldn't be functional, i think that much is obvious. Libraries like this one _add_ functionality by scanning for patterns, tags, etc. But in my opinion, if something in that comment is detected, but not supported, it should be ignored by default. It's non-functional code by its nature, so why should it suddenly start causing problems until _more_ code is added to force it back to non-functionality?

It's not my intent to sound argumentative, i'm mostly looking to learn the intention of this design, and if any alternatives might be or have been considered.

**Comment by malarzm** [comment]
> maybe someone can point me in the direction of something more current/relevant.

The best course of action is to migrate away from `doctrine/annotations` - PHP 8 gave us attributes and that's what everybody should be doing :)

**Comment by derrabus** [comment]
I agree. There won't be a better solution to this problem than migrating away from this library. Let's close the issue.
