### ISSUE TITLE
Importing classes named after common phpdoc annotations

### ISSUE THREAD

**Issue by j6s** [doctrine/annotations#317]
Since upgrading to the new `doctrine/annotations` 1.10.0 release it fails to analyze classes that use `phpdocumentor/reflection-docblock`:

```
[Semantical Error] The class "phpDocumentor\Reflection\DocBlock\Tags\Param" is not annotated with @Annotation.
Are you sure this class can be used as annotation? [...]
```

At first I thought the following in the `Param` class itself would be the issue:

```
/**
 * Reflection class for the {@}param tag in a Docblock.
 */
```

but the longer I read the error message the more I am convinced, that my class that imports `phpDocumentor\Reflection\DocBlock\Tags\Param` and then uses `@param` in docblocks is at fault: Seems like the `@param` is being interpreted as a reference to the `Param` class which is not an annotation.

I will report back to this ticket after having conducted a couple of tests.

**Comment by bwaidelich** [comment]
Yes, 1.9 => 1.10 seemed to introduce a breaking change here.
We also see
```
[Semantical Error] The class "PHPUnit\Framework\Error\Deprecated" is not annotated with @Annotation.
```
in our CI

**Comment by albe** [comment]
I can confirm there is some breaking change in the new release, leading to wrong classes be autoloaded for annotations.

For example here:
https://travis-ci.org/github/neos/flow-development-collection/jobs/670069940#L996
The `@deprecated` tag in a PHPUnit test suddenly tries to load `PHPUnit\Framework\Error\Deprecated` as an annotation class, which is obviously wrong.

**Comment by j6s** [comment]
Confirming my suspicion: Changing 

```
use phpDocumentor\Reflection\DocBlock\Tags\Param;
```

to 

```
phpDocumentor\Reflection\DocBlock\Tags\Param as DocumentorParam;
```

Fixes the issue - `@param` in docblocks is being resolved to the `Param` class reference

**Comment by stof** [comment]
@alcaeus could it be caused by https://github.com/doctrine/annotations/pull/316 ?

**Comment by albe** [comment]
Either that or https://github.com/doctrine/annotations/pull/271 - which I think is more likely, as it adds the autoloading fallback, which in turn sounds like a good explanation for loading `@param` as the class that was imported.

**Comment by alcaeus** [comment]
> @alcaeus could it be caused by #316 ?

@j6s @albe @bwaidelich could you please test 1.9.0 and see if that fixes the issue? The PR mentioned by @stof was not included in that release, so this would help me figure out where this goes wrong.

I'll see if I can cook up a test case in the meantime.

**Comment by j6s** [comment]
I can confirm, that 1.9.0 does not have this issue - the issue was introduced with 1.10.0

**Comment by alcaeus** [comment]
Thanks! That narrows it down to two potential PRs and I've got a good suspicion that neither is responsible by itself. Please sit tight for a few minutes and use a release < 1.10 in the meantime. Sorry for the disruption.

**Comment by alcaeus** [comment]
Can you please check the changes from #318 to see if it fixes this for you or breaks anything else? Thanks!

**Comment by bwaidelich** [comment]
@alcaeus Yes, I can confirm that #318 fixes the issue for us. Thanks for the swift reaction!

**Comment by alcaeus** [comment]
1.10.1 is released. Thanks for bringing this to our attention and confirming the fix! 🎉
