### ISSUE TITLE
[Semantical Error] The annotation was never imported

### ISSUE THREAD

**Issue by turtle0x1** [doctrine/annotations#325]
Hi

I was developing against `dev-master` (I know - stupid) 

I have a (lots) of classes that looks like this

```php
namespace SomeNamespace;

use Symfony\Component\Routing\Annotation\Route;

class CreateUserController
{
    public function __construct() {
    }
    /**
     * @Route("/api/common/users/create", methods={"POST"},  name="Create a user")
     */
    public function create() {
    }
}
```

That is now triggering 
>[Semantical Error] The annotation \@Symfony\Component\Routing\Annotation\Route in method  Somenamespace::create () was never imported. Did you maybe forget to add a use\ statement for this annotation?

This was not the case until recently I know the commit 0f960c13d955119807c16853c6f7de80dd77a1ba worked fine (I tried to just make composer user this commit but composer can't seem to use this commit)

Im using the library as follows (but see I now need to change the namespace to `\Doctrine\Common\Annotations\AnnotationReader()`

```php
$reader = new \Doctrine\Annotations\AnnotationReader();
$r = // Reflect some method
$route = $reader->getMethodAnnotation($r, "Symfony\Component\Routing\Annotation\Route");
```

I also notice the branch alias has changed ? In the repository where this still works I have the following in my composer.lock

```
        "extra": {
                "branch-alias": {
                    "dev-master": "2.0.x-dev"
                }
            },
``` 

In the one where its broken I have

```
            "extra": {
                "branch-alias": {
                    "dev-master": "1.11.x-dev"
                }
            },
```

**Comment by alcaeus** [comment]
Master was reset to a 1.x state as 2.0-dev was in a very unhealthy state with nobody working on it for more than a year. If you must, you can grab a copy of the old master from https://github.com/alcaeus/annotations/tree/previous-master, but I would suggest not relying on that state as we don’t know when and if that work will be released.

**Comment by turtle0x1** [comment]
Thanks alot, I am actually going to need that for a little while (I have a lot to fix), I dont know if you are a dev but do you know how to fix the error im getting (the 2.X had the fix for this issue which is why I used it in the first place, I remember tracking it down when I set this up)

**Comment by turtle0x1** [comment]
Fixed in https://github.com/doctrine/annotations/pull/323
