### ISSUE TITLE
Request for documentation

### ISSUE THREAD

**Issue by cnizzardini** [doctrine/annotations#328]
The documentation on this page https://www.doctrine-project.org/projects/doctrine-annotations/en/1.10/index.html specifies that I can supply arrays, classes, and arrays of classes. It would be excellent if examples of each were provided.

**Comment by greg0ire** [comment]
>  I can supply arrays

Ctrl+F arrays on the page you linked gives no result. Can you please elaborate?

**Comment by cnizzardini** [comment]
On this page: https://www.doctrine-project.org/projects/doctrine-annotations/en/1.10/custom.html#custom-annotation-classes

There are no examples of implementing this:

```
    /** @var SomeAnnotationClass */
    public $annotation;

    /** @var array<integer> */
    public $arrayOfIntegers;

    /** @var array<SomeAnnotationClass> */
    public $arrayOfAnnotations;
```

**Comment by greg0ire** [comment]
This is getting a bit clearer.

> examples of implementing this

What would you expect exactly? Showing an example of a class using the `Bar` annotation with all the 3 properties above? I see there is an example below: https://www.doctrine-project.org/projects/doctrine-annotations/en/1.10/custom.html#usage , maybe it could be completed to use the 3 properties?

**Comment by cnizzardini** [comment]
Yes, I think that would be helpful for some people. Examples of each.

**Comment by greg0ire** [comment]
Great. Please consider contributing that.
