### ISSUE TITLE
PHP code creating login

### ISSUE THREAD

**Issue by Matooo1** [doctrine/annotations#333]
if (isset($_POST['login'])) {

		$login_sql="SELECT * FROM uporabnik WHERE username='".$_POST['username']."' AND password='".sha1($_POST['password'])."'";

		if($login_query=mysqli_query($connect1, $login_sql)){ 

			$login_rs=mysqli_fetch_assoc($login_query);
			$_SESSION['admin']=$login_rs['username']; //THIS IS LINE 8

		}
	}

The error says: 
Notice: Trying to access array offset on value of type null in
 C:\xampp\htdocs\nike\admin.php on line 8

Line 8 is by the comment

**Comment by malarzm** [comment]
This has nothing to do with doctrine/annotations package. If you seek general help please try stackoverflow.com
