### ISSUE TITLE
Aliasing breaks with PHP8

### ISSUE THREAD

**Issue by shyim** [doctrine/annotations#339]
Error:
Uncaught Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "@ORM\Table" in class Shopware\Models\Shop\Shop was never imported.

```
use Doctrine\ORM\Mapping as ORM;
/**
 * @ORM\Table(name="s_core_shops")
 * @ORM\Entity(repositoryClass="Repository")
 */
```

Without alias it works:

```
use Doctrine\ORM\Mapping as ORM;
/**
 * \Doctrine\ORM\Mapping\Table(name="s_core_shops")
 * \Doctrine\ORM\Mapping\Entity(repositoryClass="Repository")
 */
```

**Comment by stof** [comment]
Please give the exact version of the PHP build you use. PHP 8 is not a thing yet, so this is not precise enough.

For instance, I'm 99% sure that https://wiki.php.net/rfc/namespaced_names_as_token will impact the parsing of use statements in this package (breaking it until the implementation accounts for the new token type), but this change is not yet merged into PHP 8 nightly, as it is still in voting phase.

**Comment by shyim** [comment]
How can I see more information then ``PHP 8.0.0-dev (cli) (built: Jul 29 2020 04:56:30) ( NTS )``?
I am using the Docker image https://hub.docker.com/r/phpdaily/php . It seems to just build the master branch every day

**Comment by ondrejmirtes** [comment]
@stof The linked RFC is most likely the reason for the breakage, the pull request is merged despite the RFC status on the wiki page.

**Comment by stof** [comment]
oh, then it is definitely the reason.

**Comment by shyim** [comment]
With this patch it seems to work for my project. But the tests are still failing in this repository, cause the alias is wrong. It needs much more work I guess :sweat_smile: 

```
Index: lib/Doctrine/Common/Annotations/TokenParser.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- lib/Doctrine/Common/Annotations/TokenParser.php	(revision eb0bfd40dbe96422211f26324c3c8a0b1e5026be)
+++ lib/Doctrine/Common/Annotations/TokenParser.php	(date 1596183240445)
@@ -65,6 +65,17 @@
         token_get_all("<?php\n/**\n *\n */");
 
         $this->numTokens = count($this->tokens);
+
+        // Compatibility defines for PHP < 8.0.
+        if (!defined('T_NAME_QUALIFIED')) {
+            \define('T_NAME_QUALIFIED', -2);
+        }
+        if (!defined('T_NAME_FULLY_QUALIFIED')) {
+            \define('T_NAME_FULLY_QUALIFIED', -3);
+        }
+        if (!defined('T_NAME_RELATIVE')) {
+            \define('T_NAME_RELATIVE', -4);
+        }
     }
 
     /**
@@ -106,8 +117,14 @@
         $statements = [];
         $explicitAlias = false;
         while (($token = $this->next())) {
-            $isNameToken = $token[0] === T_STRING || $token[0] === T_NS_SEPARATOR;
-            if (!$explicitAlias && $isNameToken) {
+            $isNameToken = $token[0] === T_STRING || $token[0] === T_NS_SEPARATOR || $token[0] === T_NAME_QUALIFIED || $token[0] === T_NAME_FULLY_QUALIFIED;
+            if ($token[0] === T_NAME_QUALIFIED) {
+                $class .= $token[1];
+                $alias = $token[1];
+            } else if ($token[0] === T_NAME_FULLY_QUALIFIED) {
+                $class .= $token[1];
+                $alias = $token[1];
+            } elseif (!$explicitAlias && $isNameToken) {
                 $class .= $token[1];
                 $alias = $token[1];
             } else if ($explicitAlias && $isNameToken) {
@@ -172,7 +189,7 @@
     public function parseNamespace()
     {
         $name = '';
-        while (($token = $this->next()) && ($token[0] === T_STRING || $token[0] === T_NS_SEPARATOR)) {
+        while (($token = $this->next()) && ($token[0] === T_STRING || $token[0] === T_NS_SEPARATOR || $token[0] === T_NAME_QUALIFIED)) {
             $name .= $token[1];
         }
 ```

**Comment by jkufner** [comment]
@shyim Such a solution seem rather ugly, as it affects the global namespace. I think it would be better to check PHP version and use only relevant tokens in each `if` branch. Undefined constants are fine as long as they are not evaluated, and it would be obvious what is going.

**Comment by shyim** [comment]
Or two parser classes? :thinking:

**Comment by jkufner** [comment]
I was thinking about that too, but if it is only this one case (and one if), the overhead would not be worth it.

**Comment by shyim** [comment]
Hey,
can we get an Release, so I can continue making the application ready for PHP 8

**Comment by jkufner** [comment]
@shyim The absence of a release should not block you ;)

You can add local repositories to `~/.composer/config.json` and use them instead of the real ones.

**Comment by shyim** [comment]
I have to use minimum-stability dev and require the branch. Otherwise I can't test it in the CI with phpunit / behat

**Comment by greg0ire** [comment]
Sure! https://github.com/doctrine/annotations/releases/tag/1.10.4
