### ISSUE TITLE
PHPUnit needs to be upgrade

### ISSUE THREAD

**Issue by stof** [doctrine/annotations#340]
Currently, the project relies on PHPUnit 7.5. This version triggers deprecation warnings in PHP 8 (which make the testsuite fail)

**Comment by greg0ire** [comment]
I wrongly assumed that `composer.lock` was under version control but it isn't anymore. Things should be easier, but first, we have to fix the build on the stable branch, it is broken.

**Comment by greg0ire** [comment]
I'm attempting to fix the build with #341
