### ISSUE TITLE
Annotation not being cached

### ISSUE THREAD

**Issue by njovanovich** [doctrine/annotations#373]
I think I found a bug in doctrine annotations

ErrorException
in vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/CachedReader.php (line 126)

This error exception happens to me.  I can fix it 

vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/CachedReader.php 
`Line 113 - if (!($annots = $this->fetchFromCache($cacheKey, $class))) {`

Using the not case not the false === that is in the code. 

I discovered this bug doing an assessment for a company I want to work for.  The code is published @ https://github.com/njovanovich/norwex

At the moment the code is patched and the vendor dir is not ignored.  You can reproduce the bug by deleting the vendor dir and rebuilding composer.

**Comment by lcobucci** [comment]
@njovanovich that sounds rather odd, would be able to isolate the problem and reproduce it in a test case for our suite? Bear in mind that the code is slightly different now (not much, really): https://github.com/doctrine/annotations/blob/0efa091f05412d46ac0cadc46f2f54302dae7741/lib/Doctrine/Common/Annotations/CachedReader.php#L110-L116

Perhaps https://github.com/doctrine/annotations/blob/1.10.x/tests/Doctrine/Tests/Common/Annotations/CachedReaderTest.php is a good starting point for your exploration?

**Comment by njovanovich** [comment]
I just had some time to revist this issue and it seems to be working fine as of 1.13.1.

Thanks
