### ISSUE TITLE
Reconsider NamedArgumentConstructorAnnotation

### ISSUE THREAD

**Issue by derrabus** [doctrine/annotations#379]
I would like to use the named constructor arguments feature in Symfony for some of the annotations there. We already have altered the constructors of most annotation classes in order to enable them to be used as attributes with named arguments as well. By leveraging this new way of constructing annotation classes, I expect to simplify those constructors again.

However, in order to do so, I have to add this marker interface `NamedArgumentConstructorAnnotation` to my annotation class. That‘s kind of a first because so far, we can construct instances of our annotation classes, even if the `doctrine/annotations` library is not installed. This becomes even more important if one fine day we wanted to build an application that uses PHP Attributes instead of Doctrine annotations everywhere.

Because of that, I wonder if we could find an alternative way to flag a class for named argument construction. Maybe we could achieve this with a `@NamedArgumentConstructor` annotation that has the same effect as the marker interface.

**Comment by greg0ire** [comment]
> That‘s kind of a first because so far, we can construct instances of our annotation classes, even if the doctrine/annotations library is not installed.

Is that a scenario that currently happens somewhere? Can you give an example?

> This becomes even more important if one fine day we wanted to build an application that uses PHP Attributes instead of Doctrine annotations everywhere.

Can you elaborate? I don't see what the issue is…

**Comment by beberlei** [comment]
@derrabus it sounds like a sensible suggestion to provide a new internal annotation to provide the same behavior. I would merge a PR in that regard.

**Comment by derrabus** [comment]
Sorry for the late reply @greg0ire.

> Is that a scenario that currently happens somewhere? Can you give an example?

Yes, basically all of Symfony's validator constraints work that way.

Now with PHP attributes, this is extended to routing and the serializer. Basically, if you switch from a `@Route` annotation to a `#[Route]` attribute, you can drop `doctrine/annotations` if you don't need it elsewhere.

> Can you elaborate? I don't see what the issue is…

If my annotation class needs to implement a marker interface, that interface has to be present. For instance, this is how our `@Route` annotation class currently looks like:

https://github.com/symfony/symfony/blob/v5.2.1/src/Symfony/Component/Routing/Annotation/Route.php

It can be used as annotation and as attribute. And the app developer can chose not to use it at all, so `doctrine/annotations` is not a mandatory dependency of `symfony/routing` because we don't want to clutter an application's vendor folder with dependencies the app might not need.

So, right now you can annotate a controller action like this to configure a route for it:

```php
#[Route('/my/route')]
function myAction(Request $request): Response
{
    // …
}
```

Again, `doctrine/annotations` is not needed here to process this piece of code.

Now, if you take a look at the `Route` class, you see that we're dealing with extra complexity here because we allow the constructor to be called with an array (for compatibility with `doctrine/annotations`) and with named arguments (for compatibility with PHP attributes).

The `NamedArgumentConstructorAnnotation` feature as I understand it would rid us of this complexity because we can deprecate and drop the first mode and switch to named arguments completely.

Now, if I add the marker interface to my `Route` class (`class Route implements NamedArgumentConstructorAnnotation`), the interface must be present when loading the class. That means that even if I want to use that class as a PHP attribute, I would suddenly need `doctrine/annotations` to be present, only to have that interface.

**Comment by greg0ire** [comment]
Thanks for the explanation, I think I get it now :)

**Comment by derrabus** [comment]
I gave it a try: #391
