### ISSUE TITLE
[FEATURE] allow static function 

### ISSUE THREAD

**Issue by Lenny4** [doctrine/annotations#384]
I have notice in `lib/Doctrine/Common/Annotations/DocParser.php` `private function PlainValue` that it's allow to pass 3 type of DocLexer as below:
```php
if ($this->lexer->isNextToken(DocLexer::T_OPEN_CURLY_BRACES)) {
    return $this->Arrayx();
}

if ($this->lexer->isNextToken(DocLexer::T_AT)) {
    return $this->Annotation();
}

if ($this->lexer->isNextToken(DocLexer::T_IDENTIFIER)) {
    return $this->Constant();
}
```
With this code you can then pass (for instance) constant to your annotation like that:
```php
@SomeAnnotation(prop=MyClass::SOME_CONSTANT)
```
But it's impossible to pass a static function with no parameters like this:
With this code you can then pass (for instance) constant to your annotation like that:
```php
@SomeAnnotation(prop=MyClass::getClassPathStaticFunction)
```
```php
// src/MyClass.php
public static function getClassPathStaticFunction(){
    // your code
}
```
I wonder if I can implement this functionality by adding a new `DocLexer` that allow to pass static function with no param as my example above and call it like this:
```php
<?php
if ($this->lexer->isNextToken(DocLexer::T_OPEN_CURLY_BRACES)) {
    return $this->Arrayx();
}

if ($this->lexer->isNextToken(DocLexer::T_AT)) {
    return $this->Annotation();
}

if ($this->lexer->isNextToken(DocLexer::T_IDENTIFIER)) {
    return $this->Constant();
}

if ($this->lexer->isNextToken(DocLexer::T_STATIC_FUNCTION)) {
    // StaticFunction need to be create in lib/Doctrine/Common/Annotations/DocParser.php
    return $this->StaticFunction();
}

```
Or maybe it's already possible to pass a static function but I didn't find this feature yet.

**Comment by stof** [comment]
`MyClass::getClassPathStaticFunction` is not a constant in your code snippet but a static function. I fail to understand your feature request as you say that would then allow passing a constant (which is already possible, for things which are actually constants)

**Comment by Lenny4** [comment]
Hi @stof it wasn't my point, let's imagine I have this class:
```php
class MyClass
{
    const MY_CONST = ['some-data'];

    public static function myStaticFunction()
    {
        $data =  ['other-data']';
        return $data;
    }
}
```
I want to be able to do:
```php
@SomeAnnotation(prop=MyClass::MY_CONST)
@OtherAnnotation(prop=MyClass::myStaticFunction)
```
Now I need to check if it's a constant or a static function, and if it is a static function I can call it this way:
```php
call_user_func('MyClass' . '::myStaticFunction');
```

This feature would be usefull if you don't want to pass static data, which depends on the database or an API.

**Comment by stof** [comment]
but that's the same in PHP code. Constants and static functions are **never** usable in the same way.

And doctrine/annotations does not allow you to call a callable to set the value of a property (not even counting the case that you don't want it to look like a function call)

**Comment by Lenny4** [comment]
> but that's the same in PHP code. Constants and static functions are never usable in the same way.

Yes that why I need to check if it's a constant or a static function
```php
$myClass = 'MyClass';
$constantOrStaticFunction = 'CHECKED_CONSTANT';
if (defined($myClass . '::' . $constantOrStaticFunction)) {
    return constant($myClass . '::' . $constantOrStaticFunction);
}
// ===================OTHER EXAMPLE==================================
$myClass = 'MyClass';
$constantOrStaticFunction = 'myStaticFunction';
if (is_callable($myClass, $constantOrStaticFunction)) {
    return call_user_func($myClass . '::' . $constantOrStaticFunction);
}
```
> And doctrine/annotations does not allow you to call a callable to set the value of a property

I want to implement this feature.

> not even counting the case that you don't want it to look like a function call

In this case we can force the user to add `()` to be sure that he want to use a function:
```php
@OtherAnnotation(prop=MyClass::myStaticFunction())
```
```php
function endsWith($string, $endString) 
{ 
    $len = strlen($endString); 
    if ($len == 0) { 
        return true; 
    } 
    return (substr($string, -$len) === $endString); 
} 
// ===================OTHER EXAMPLE==================================
$myClass = 'MyClass';
$constantOrStaticFunction = 'myStaticFunction';
if (is_callable($myClass, $constantOrStaticFunction)) {
    if(!endsWith($constantOrStaticFunction,'()')) {
        throw new Exception('some error'); // I throw an Exception for the example but it rather be a AnnotationException
    }
    return call_user_func($myClass . '::' . $constantOrStaticFunction);
}
```

**Comment by stof** [comment]
Annotations are meant to be cacheable. Allowing to call arbitrary callables (well, restricted to static methods in your proposal) would break that entirely. Note that PHP 8 attributes don't allow that either.

to me, it seems like you are trying to use annotations for something that they are not meant to support.

**Comment by beerline** [comment]
Hi guys!
@stof but why value of static methods can't be cached? 

Example:
Lets say we have a class for custom messages. We want to use message from `composeDefaultMessage` as a constraint violation message
```php
class GreaterThan
{
    public static function composeDefaultMessage(float $value): string
    {
        return 'This value should be greater then ' . $value . '';
    }
}
```

Useage:
```php
class DataClass {
    /**
     * @Assert\Length(min=11, max=20, minMessage=GreaterThan::composeDefaultMessage(11))
     */
    private string $text;
}
```
it is possible to evaluate value of `GreaterThan::composeDefaultMessage(11)` and put in the cache.

Basically, we can use `loadValidatorMetadata()` for this purpose and it will work, but it is seem little bit messy and field name duplication.
```php
class DataClass {

    private string $text;

    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        $metadata->addPropertyConstraint(
            'text',
            new Assert\Length(
                [
                    'min' => 11,
                    'max' => 20,
                    'minMessage' => GreaterThan::composeDefaultMessage(11)
                ]
            )
        );
    }
}
``` 

So if to get opportunity to use static methods in annotation it will be super cool

**Comment by stof** [comment]
@beerline you are comparing different things. `loadValidatorMetadata` has nothing to do with the annotation reader. you are not talking about the same layer of caching here

**Comment by beerline** [comment]
@stof, thank you for you response.
lets forget about `loadValidatorMetadata`.

but still, why value of static method can't be cached? As far i get from discussion, it is main point against implement feature with static method call in annotations.

Basically retrieving values of static methods is pretty the same as for constant.
