### ISSUE TITLE
Compatible with php8 attributes syntax

### ISSUE THREAD

**Issue by Yurunsoft** [doctrine/annotations#387]
PHP 8 has been released

![image](https://user-images.githubusercontent.com/20104656/100402518-6d7c7500-3097-11eb-8a5b-01539ed8daf4.png)

**Comment by Xiphin** [comment]
Looking forward...

**Comment by diankemao** [comment]
向前看...

**Comment by stof** [comment]
Based on the experience we had in Symfony, the annotation classes need some rework to be usable as PHP attributes (not even counting the fact that annotations can be nested while attributes cannot for now). So I'm not sure it is feasible nor desirable for doctrine/annotations to switch between attributes and phpdoc-based annotations automatically.
And attributes don't need a reader like doctrine/annotations. The Reflection API already provides a native reading API for them.

**Comment by pounard** [comment]
That may be a big help for building forward-compatible code, but if Doctrine annotations are different by design than PHP core one, I'll understand.

**Comment by chriskapp** [comment]
Yes, the idea would be cool that the `doctrine/annotations` library uses PHP-Doc annotations for 7.x code and for 8.x it tries to load the data from native annotations. This would automatically add native annotations support for many apps using this lib. But for this we would also need to add the fitting `#[Attribute(...)]` annotations etc. to the doctrine annotations. But if this is not possible we can always add both PHP doc annotations and native annotations to be compatible for 7.x and 8.x code, or we make a hart cut and switch directly to native annotations without 7.x support. In the end we dont need this library anymore if all code runs on >=8.0.

**Comment by beberlei** [comment]
Please see https://github.com/doctrine/orm/pull/8266 for our progress on Attributes for Doctrine ORM.

This library will not make any attempts at providing a layer that automatically maps between Doctrine Annotations and PHP 8 attributes, because they are different in details and this must be accounted for by every user of attributes.

**Comment by koriym** [comment]
I have created a reader for this purpose.
https://github.com/koriym/Koriym.Attributes

**Comment by kgrosvenor** [comment]
[Semantical Error] The annotation "@ORM\Entity" in class App\Entity\Client was never imported, any ideas? I have updated the annotation lib to where php 8 support is...
