### ISSUE TITLE
Composer up with dev stability fails because of headless commit

### ISSUE THREAD

**Issue by jderusse** [doctrine/annotations#398]
Reproducer:

```shell
composer init
composer req doctrine/annotations
composer config minimum-stability dev
composer up
```
outputs
```
  - Installing doctrine/annotations (dev-master 5cb4064): Cloning 5cb4064410
    5cb4064410e57ffd3ed5583cdb2baa6f1a1fa204 is gone (history was rewritten?)
```

In packagist, the dev-master branch points to 1.12.x-dev (https://packagist.org/packages/doctrine/annotations#dev-master)
But this reference only appear in this commit https://github.com/doctrine/annotations/commit/5cb4064 which does not belong to any branch.
The current 1.12.x branch is an alias to `1.11.x-dev`: https://github.com/doctrine/annotations/blob/6c0fa43b0369b9c0cf11d9ec97b6cd9936067fd2/composer.json#L44

**Comment by greg0ire** [comment]
Some repositories included this one were migrated away from master, meaning at some point we I removed that branch. That must be it. I don't know how we can get rid of that `dev-master` pointed, but it should no longer exist.

**Comment by jderusse** [comment]
ping @Seldaek any idea?

**Comment by greg0ire** [comment]
I took care of the branch alias that was on 1.12.x, in case it's related, but the docs say it should be inconsequential.

**Comment by greg0ire** [comment]
Well… looks like `dev-master` is gone now, so… I don't know what to think, but it is fixed according to Packagist and your reproducer. Thanks for reporting this 👍

**Comment by jderusse** [comment]
thank you @greg0ire

**Comment by stof** [comment]
When deleting a branch on github, Packagist has a delay before actually deleting it, to avoid issues where the github API would be temporary unreliable when reporting branches (years ago, when starting packagist, this was happening a lot)

**Comment by greg0ire** [comment]
I deleted `master` ages ago, I don't think it is related to that, unless my actions somehow shortened the delay on the pre-existing event you describe.

**Comment by stof** [comment]
@greg0ire what could have happened is that there was no pushes in the repo after the delay was over (and so no new processing removing the branch) until you made your changes (repos that are auto-updated by the webhook are updated only when a push is done, or by a fallback cron running very rarely, not on each run of the cron dealing with non-auto-updated packages)

**Comment by greg0ire** [comment]
That sounds likely 👍
