### ISSUE TITLE
When will be released version 1.12?

### ISSUE THREAD

**Issue by Aerendir** [doctrine/annotations#403]
I've submitted two PRs that fix some issue when reading annotations of Rector and Phan:

- https://github.com/doctrine/annotations/pull/386
- https://github.com/doctrine/annotations/pull/362

They are currently merged, but not yet released.

This is causing me a lot of issue because I'm in a dependency hell and I'm not able to find an installable set of packages.

I'm forced to use `doctrine/doctrine-bundle:2.0.10`, in this exact version and now other bundles I'm using are trying to install higher versions and Composer cannot install them...

It is very frustrating 😔

Releasing the version 1.12 of this package will solve all the issues as I will be able to update and also to make the static analysis to work properly.

I'm not the one in this situation, also if I'm the only one that is writing...

UPDATE

In the mean time I'm working around this problem requiring the dev version of the 1.12 version:

```console
composer req doctrine/annotations:1.12.x-dev
```

**Comment by greg0ire** [comment]
We can release as soon as https://github.com/doctrine/annotations/pull/402 gets merged I think.

**Comment by Vincz** [comment]
Hey guys! When can we expect the 1.12 release?

**Comment by greg0ire** [comment]
I'm on it.

**Comment by greg0ire** [comment]
https://twitter.com/greg0ire/status/1363104915611148293
