### ISSUE TITLE
Annotation reader can't read annotations from relation entity

### ISSUE THREAD

**Issue by bastien70** [doctrine/annotations#415]
I have set up a custom annotation called **Uploadable**.

Here is how I check that the **@Uploadable** annotation is present on an entity:

```php
use Doctrine\Common\Annotations\AnnotationReader;

class UploadAnnotationReader
{
    private AnnotationReader $reader;

    public function __construct(private EntityManagerInterface $manager){
        $this->reader = new AnnotationReader();
    }

    /**
     * @throws \ReflectionException
     */
    public function isUploadable($entity):bool
    {
        $reflection = new \ReflectionClass(get_class($entity));

        return $this->reader->getClassAnnotation($reflection, Uploadable::class) !== null;
    }
```

When I pass in parameter an entity (which does have the annotation that I created) obtained either directly from the database, or from the Symfony paramConverter, then the AnnotationReader is able to see this annotation.

On the other hand, if I get this entity back through a relation from another entity, oddly, it won't work anymore!

```php
$entityA = $manager->getRepository(...)....;
$myService->isUploadable($entityA); // return true
```

```php
$entityB = $manager->getRepository(...)....;
$myService->isUploadable($entityB->getEntityA()); // return false
```

```php
$entityB = $manager->getRepository(...)....;
$entityA = $entityB->getEntityA();

$myService->isUploadable($entityB->getEntityA()); // return true
```

Very weird..

**Comment by stof** [comment]
Well, in case you have a doctrine proxy object, `get_class($entity)` won't be the entity class itself, bu the proxy child class (which indeed does not have the annotation). there is no bug in the annotation reader here, but in your own code.

When dealing with Doctrine entities, have a look at `Doctrine\Common\Util\ClassUtils::getClass`.

**Comment by bastien70** [comment]
Yes it works ! Thank you very much ! :D
