### ISSUE TITLE
Possible BC break as parameters are not case insensitive anymore

### ISSUE THREAD

**Issue by shyim** [doctrine/annotations#421]
Upgrade from 1.11.1 to 1.13.0 made the parameters in the Annotations case sensitive and break now with a fatal error.

**Comment by greg0ire** [comment]
Can you please contribute a failing test case for this? I found nothing obvious in the comparison: https://github.com/doctrine/annotations/compare/1.11.1...1.13.0

**Comment by derrabus** [comment]
Closing due to the lack of feedback.
