### ISSUE TITLE
Argument 8 passed to Doctrine\ORM\Mapping\Column::__construct

### ISSUE THREAD

**Issue by krajcikondra** [doctrine/annotations#432]
Hi, I have installed

doctrine/orm 2.10.11
doctrine/annotations 1.13.2

but I get following error:

`
Argument 8 passed to Doctrine\ORM\Mapping\Column::__construct() must be of the type array, string given, called in /var/www/html/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php on line 971
`

Have somebody same problem?

**Comment by stof** [comment]
Well, I suspect that you wrote an invalid `@ORM\Column` annotation somewhere in your code (the stack trace might help you if it shows the value of arguments passed to the annotation reader), configuring the wrong type of value of the `options` argument

**Comment by krajcikondra** [comment]
Omg, you are right.

I had bad syntax
```
         * @ORM\Column(type="boolean", nullable=false, options="{default=1}") // bad
	 * @ORM\Column(type="boolean", nullable=false, options={"default" : 1}) // corect
```

Thanks very much
