### ISSUE TITLE
Trouble parsing a string that contains curly braces

### ISSUE THREAD

**Issue by olsona-hologram** [doctrine/annotations#448]
Raising an issue from Swagger-PHP over here: https://github.com/zircote/swagger-php/issues/1004

When parsing a string literal that contains curly braces (example: `"{\"formConfig\":123}"`), it's not clear how to make the lexer understand that it is in fact a string literal. Is there any advice you can give me on this front, or is this a bug?

**Comment by stof** [comment]
In Doctrine annotations, quotes are escaped by doubling them, not by adding a `\` before them.

**Comment by olsona-hologram** [comment]
Thank you, that's what I needed!
