### ISSUE TITLE
Nested annotation in ignored namespace appears in result as false, breaking Symfony validation

### ISSUE THREAD

**Issue by DieterHolvoet** [doctrine/annotations#450]
`DocParser::PlainValue` always returns the result of `DocParser::Annotation`, even if it returns false because of an invalid/ignored annotation. `DocParser::Annotations` on the contrary checks the return value and returns early if it's false, actually ignoring the annotation, which seems like the right behaviour.

This causes an issue where a nested annotation in an ignored namespace appears in the parsing result as false, breaking Symfony validation with the following error:

`
An error occurred while instantiating the annotation @Assert\Collection declared on property SomeClass::$someProperty: "The value "" is not an instance of Constraint in constraint "Symfony\Component\Validator\Constraints\Required".".
`

**Comment by malarzm** [comment]
I took the liberty of copying issue's description to the PR to have all information in one place.
