### ISSUE TITLE
[1.13.3 to 1.14.0] Undefined array key "type"

### ISSUE THREAD

**Issue by ruudk** [doctrine/annotations#462]
When using PHP-CS-Fixer the following code breaks:

```php
<?php

declare(strict_types=1);

namespace App;

final class SomeTest extends BaseTest
{
    /**
     * @test
     * @doesNotPerformAssertions
     */
    public function it_should_validate() : void
    {

    }
}
```

```
        [ErrorException]
        Undefined array key "type"

      {closure}()
        in vendor/friendsofphp/php-cs-fixer/src/Doctrine/Annotation/Tokens.php at line 74
      PhpCsFixer\Doctrine\Annotation\Tokens::createFromDocComment()
        in vendor/friendsofphp/php-cs-fixer/src/AbstractDoctrineAnnotationFixer.php at line 62
      PhpCsFixer\AbstractDoctrineAnnotationFixer->applyFix()
        in vendor/friendsofphp/php-cs-fixer/src/AbstractFixer.php at line 75
```

I'm seeing this more when using short tags like `@doesNotPerformAssertions` or `@BeforeScenario` (Behat).

**Comment by icanhazstring** [comment]
This happens here:
https://github.com/doctrine/annotations/compare/1.13.3...1.14.0#diff-862964759d0cedd01fd3a7d6cb59515e2a404c78450e53022018016ab15ef7dfR133-R138

Seems like `Lexer::peek()` previously returned `null` in some cases.
Now its an empty array. That is a breaking change right now.

**Comment by alcohol** [comment]
Yeah I just reported the same at https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6706

**Comment by greg0ire** [comment]
> That is a breaking change right now.

Not a voluntary one though, it's just me being careless. Don't worry, it's going to be fixed.

**Comment by greg0ire** [comment]
Let me know if https://github.com/doctrine/annotations/pull/463 works for you.
