### ISSUE TITLE
@required was never imported

### ISSUE THREAD

**Issue by safwanghamrawi** [doctrine/annotations#475]
We have juste  install a Symfony 5.4 with php 7.4 (7.4.25).
when we create a route extend AbstractController we have an error  @required was never imported.
doctrine/annontation installed was 2.*.

We resolve the issue by installing an older version doctrine/annotations:1.*

doctrine/annotations 2.0 doesn't work with php 7.4 and so it must be removed from the composer.json file

**Comment by stof** [comment]
This is actually a bug in symfony/framework-bundle when adding support for doctrine/annotations 2.0. A fix has been committed and will be part of the next Symfony release.

**Comment by safwanghamrawi** [comment]
thanks
