### ISSUE TITLE
2.0.0 unmaintained?

### ISSUE THREAD

**Issue by xcy7e** [doctrine/annotations#476]
The documentation on doctrine-projects.org states, that version 2.0.0 is unmaintained.
But it was released here only 1 month ago? Is the documentation just outdated, or what is true?

https://www.doctrine-project.org/projects/annotations.html

**Comment by greg0ire** [comment]
The documentation is outdated, I forgot to update https://github.com/doctrine/annotations/blob/2.0.x/.doctrine-project.json
