### ISSUE TITLE
Doctrine/attributes comming? 

### ISSUE THREAD

**Issue by AbdullahAlhariri** [doctrine/annotations#482]
I curious to know if you are working on a new version of this repo, to support attributes? 
Or is there already a solution? 
I would like to update my current custom annotation to attributes in symfony 6.2 & php 8.1 project

**Comment by stof** [comment]
The reader for attributes is `ReflectionClass` and `ReflectionMethod` already. There is no reason to create a userland parser for them (that's the whole point).
