### ISSUE TITLE
filemtime warning because of eval'd code

### ISSUE THREAD

**Issue by yard-mschwartz** [doctrine/annotations#492]
This ticket concerns `1.13.*` and `2.*` of this package.

Currently, I'm trying to upgrade an application from Symfony 5.4 to Symfony 6.0 (and then later to the most recent 6.x).

This halted my progress:

```
$ symfony console cache:clear

In PsrCachedReader.php line 222:
                                                                                                                                                                          
  Warning: filemtime(): stat failed for /home/.../my-project/vendor/lexik/jwt-authentication-bundle/Security/Authenticator/ForwardCompatAuthenticatorTrait.php(14) : eval()'d code
```

Turns out a solution was already suggested by someone else in #436, but this solution was never merged. Two changes in `lib/Doctrine/Common/Annotations/PsrCachedReader.php` solve the issue for me:

* Adding `use function is_file;` on top
* Changing `[$filename ? filemtime($filename) : 0]` to `[is_file($filename) ? filemtime($filename) : 0]` in two places

Would this be a good improvement for the package, or am I missing something?

P.S. I'll also try to upgrade `lexik/jwt-authentication-bundle` to `3.*` once it becomes available, because the `ForwardCompatAuthenticatorTrait` only seems to exist in `2.*`.

**Comment by malarzm** [comment]
The best course of action is to migrate away from `doctrine/annotations` and use [attributes](https://www.php.net/manual/en/language.attributes.overview.php) :)

**Comment by yard-mschwartz** [comment]
Yes, fair point. I am aware of this. It would help me and potentially others if this could be done in steps, but it's likely that I will try to move on in one go later this week.

**Comment by derrabus** [comment]
Feel free to submit a PR with the proposed fix and a test that reproduces the issue.

**Comment by stof** [comment]
Fixed in https://github.com/doctrine/annotations/pull/494
