### ISSUE TITLE
Annotations that are indented by tab are not processed.

### ISSUE THREAD

**Issue by josefsabl** [doctrine/annotations#68]
Annotations that are indented by tab are not processed.

```
/**
 *     @ODM\Boolean
 * previous line is indented by tab
 */
public $thisWillNotBePersisted;
```

Directed from here: https://github.com/doctrine/mongodb-odm/issues/1337

**Comment by poldridge** [comment]
This only affected the first annotation in a DocBlock.

I'm not sure if this is a related issue or even an issue at all, but DocBlocks also don't seem to need * on each line. This DocBlock is fully functional:

        /** 
     @Route("/review")
    @Method("POST")
         */
