### ISSUE TITLE
Swagger (CRUD)operation with model Annotation in Yii2

### ISSUE THREAD

**Issue by bhavikac** [doctrine/annotations#71]
Hello,

I am using swagger with Yii2. i wants to know about operation ex. registration with swagger-ui for that  i have to first give text boxes etc to enter in swagger-ui or in body its self i don't know where how i can add those parameters and  how can i perform registration via swagger-ui.

**Comment by Ocramius** [comment]
Please point integration questions at stackoverflow. Issues only here :-)
