### ISSUE TITLE
Question on why class_exists avoids calling autoloaders

### ISSUE THREAD

**Issue by Lavoaster** [doctrine/annotations#72]
Hey There,

Whilst debugging an issue with the annotations on my project I found out that it was down to [this](https://github.com/doctrine/annotations/blob/master/lib/Doctrine/Common/Annotations/DocParser.php#L442) call not calling the autoloader.

I'm just wondering why is this the case?

**Comment by Ocramius** [comment]
This is covered in http://docs.doctrine-project.org/projects/doctrine-common/en/latest/reference/annotations.html#introduction

**Comment by Lavoaster** [comment]
Yeah I just saw another issue which described it and why. Thanks for commenting though. :heart:

**Comment by Ocramius** [comment]
@Lavoaster could you check your browsing history and cross-link it here for further readers, please?

**Comment by Lavoaster** [comment]
Read about it here #103, along with a solution that can override the behaviour.
