### ISSUE TITLE
DCOM-255: Add support for using TABS (for indentation) in DocBlock Annotations

### ISSUE THREAD

**Issue by guilhermeblanco** [doctrine/annotations#78]
_From @doctrinebot on October 12, 2014 20:8_

Jira issue originally created by user henrywood:

Apparently any annotation that contains at least one TAB character is ignored.

The reason/bug resides in \Doctrine\Common\Annotations\DocParser->findInitialTokenPosition() on line 351

// if the @ is preceded by a space or * it is valid

Thanks

_Copied from original issue: doctrine/common#564_

**Comment by guilhermeblanco** [comment]
_From @doctrinebot on October 13, 2014 0:24_

Comment created by @ocramius:

[~henrywood] this seems to be easily fixable by using something like `preg_match('/^(\\t](\\*)$/', $input[$pos - 1))`: can you provide a PR?

I'm just not sure about the performance impact here.

Note that JIRA screws with my regex in the quoted text, as escape sequences don't match what I entered.

**Comment by poldridge** [comment]
https://github.com/doctrine/annotations/pull/70

**Comment by Tobion** [comment]
@Ocramius I think this is fixed by #99 as well.

**Comment by Ocramius** [comment]
Indeed, closing here. Thanks for the poke, @Tobion. #99 is just #70 ported forward/rebased.
