### ISSUE TITLE
DCOM-207: Add AnnotationReader::getFunctionAnnotations()

### ISSUE THREAD

**Issue by guilhermeblanco** [doctrine/annotations#83]
_From @doctrinebot on July 9, 2013 14:26_

Jira issue originally created by user benjamin:

Currently, the annotation reader supports reading annotations on class, method and property.
This could be extended to read annotations on any kind of function, by adding the following methods:

```
public function getFunctionAnnotations(\ReflectionFunctionAbstract $function);
public function getFunctionAnnotation(\ReflectionFunctionAbstract $function, $annotationName);
```

This could be done without breaking BC in the following ways:
- Keep the Reader interface as it is
- Add a new interface, for example FullReader, that would extend Reader to add these two methods
- Add the new methods to AnnotationReader, CachedReader, etc.
- Update these classes to implement FullReader; thus they would still implement Reader and stay compatible.

Then, on the next major release (3.0.0), we could:
- Add the two methods to Reader
- Remove FullReader
- Add a note to the UPGRADE file to rename FullReader to Reader in application code.

In case you're wondering why I'm proposing this feature, I'm developing a lightweight framework, which allows any method, function, or closure to be used as a controller.
I can currently parse annotations when using a class method, but cannot provide support for annotations on the others.

That would be a great addition.
I've checked the code, and it looks like the only difficulty would be to parse "use" statements for the file where the function is declared, whereas for now it is always assumed that there is a class, and that the file name will be inferred from there. But as ReflectionFunctionAbstract provides a getFileName() method, it's technically feasible as well.

Let me know what you think!
If you have no objection to the concept, I can start working on a PR for this feature.

_Copied from original issue: doctrine/common#512_

**Comment by fabpot** [comment]
@beberlei Have you ever had time to work on this? I have the exact same needs for the exact same reasons :)

**Comment by guilhermeblanco** [comment]
@fabpot would it help if we draft a 3.0 version for now and you used "develop" until we finalize /stableize the implementation?

**Comment by fabpot** [comment]
Sure, except if 3.0 means PHP 7.0+

**Comment by guilhermeblanco** [comment]
@fabpot it would, since we plan to have all 3.0 to be php7+. Our work would be based on @FabioBatSilva Pr that moves from our custom Lexer to Hoa\Compiler. 
We can take a look at supporting php into 2.x, but that would be up to discussion... This could potentially break BC.

**Comment by fabpot** [comment]
The plan described by @beberlei seems good as far as BC is concerned.

**Comment by guilhermeblanco** [comment]
After some careful consideration, original plan needs to be updated as it has a very naive terminology. Here's my proposed plan:

- Copy contents of `Reader` into `ObjectReader`. Make interface `Reader` extends `ObjectReader`. Mark `Reader` as deprecated
- Create a new interface called `FunctionalReader` (or `FunctionReader`). Add proposed methods
- Decouple commonalities of `PhpParser::parseClass()` into private method `PhpParser::parseUseStatements()`
- Make `PhpParser::parseClass()` consume newly created method `PhpParser::parseUseStatements()`
- Add new method `PhpParser::parseFunction()` that consumes `PhpParser::parseUseStatements()`
- Implement `FunctionalReader` in `AnnotationReader`

**Comment by lennerd** [comment]
Is anybody working on this right now? Otherwise I would like to make a PR for this.

**Comment by Ocramius** [comment]
Probably worth checking https://github.com/doctrine/annotations/pull/75 first.

**Comment by lennerd** [comment]
Thanks for the very quick response. Do you think it makes sense to create the PR at all at the moment and if yes to directly work on the current v2 branch?

**Comment by Ocramius** [comment]
Possibly a better idea to target the v2 branch once it's rebased, although you can start writing a prototype already...

**Comment by lennerd** [comment]
@guilhermeblanco Quick thought about breaking BC.

Trying around with annotation `@Target` right now. I think we need to keep in mind, that people used this option to declare annotations for classes and any of their parts (methods and properties). A function is a complete new type of structure for them to consider. Also we need to change the `TARGET_ALL` constant to be also include the new target `TARGET_FUNCTION`.

Feedback and ideas welcome.

Another thing about the `Builder` class added in the 2.0 branch for #75. I'm not quite able to wrap my head around it. Can anybody explain me what the intent of this class is? cc @FabioBatSilva

**Comment by lennerd** [comment]
Head over to https://github.com/FabioBatSilva/annotations/pull/1.

**Comment by marcospassos** [comment]
Any news about this?
