### ISSUE TITLE
DCOM-229:  DocParser - add support for php5 MyClass::class call to get path of the class

### ISSUE THREAD

**Issue by guilhermeblanco** [doctrine/annotations#84]
_From @doctrinebot on January 6, 2014 7:2_

Jira issue originally created by user umed:

When I try to use in my annotations

```
Career::class
```

I get Semantical Error. Career is imported, so I dont want to use full class path name again. How about to add this feature to support by annotations?
We need to add some code like this (DocParser#Constant):

```
            if ($found) {
                 if ($const === 'class') {
                    return $className;
                 }

                 $identifier = $className . '::' . $const;
            }
        }

        if (!defined($identifier)) {
            throw AnnotationException::semanticalErrorConstants($identifier, $this->context);
        }

        return constant($identifier);
```

_Copied from original issue: doctrine/common#536_

**Comment by Majkl578** [comment]
This feature already exists:
https://github.com/doctrine/annotations/blob/c7f2050c68a9ab0bdb0f98567ec08d80ea7d24d5/lib/Doctrine/Common/Annotations/DocParser.php#L966-L970
