### ISSUE TITLE
PHP7 Grouped Use Statements ignored

### ISSUE THREAD

**Issue by blowski** [doctrine/annotations#90]
When I use the new [PHP7 grouped use statements feature](http://php.net/manual/en/language.namespaces.importing.php#language.namespaces.importing.group), Doctrine doesn't use the namespace to import the annotation. 

For example, this works:

    use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
    use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;

    class MyController
    {

        /**
         * @Route("/example")
         * @Method("GET")
         */     
        public function exampleAction() {...}

    }
But changing the namespaces to this fails:

    use Sensio\Bundle\FrameworkExtraBundle\Configuration\{
        Route, Method
    }

I'm using Doctrine Annotations 1.2.7

**Comment by Ocramius** [comment]
That sounds like a fun thing to fix (not). :-|

**Comment by Ocramius** [comment]
Needs rewrite of the logic around https://github.com/doctrine/annotations/blob/2e1b1f7597e2f647e99e96e747fcae9718ac817b/lib/Doctrine/Common/Annotations/PhpParser.php#L56

**Comment by blowski** [comment]
@Ocramius Thanks for finding the relevant code - I'll have a go at fixing it in May, assuming it's not done by then.

**Comment by kayladnls** [comment]
It's not a "solution" but couldn't you easily do: 

```
use Sensio\Bundle\FrameworkExtraBundle\Configuration as Config;

class MyController
{

    /**
     * @Config\Route("/example")
     * @Config\Method("GET")
     */     
    public function exampleAction() {...}

}
```

**Comment by blowski** [comment]
@kayladnls That's what I do at the moment, but it gets you into the difficult situation of having to use a different 'group' for each annotation group. For example, I end up with things like `@MyAnnotations\...`, `@SymfonyAnnotations` and `@DoctrineAnnotations`. 

It's not the world's biggest problem, but it would be nice.

**Comment by Ocramius** [comment]
We'd basically require switching to parser-only approach. No more regexes :-\

**Comment by yourwebmaker** [comment]
The answer is: Do not use grouped annotation. They are not even a thing in the PHP world yet.

@kayladnls "solution" is how almost developers do it today.

**Comment by Ocramius** [comment]
Yeah, we have to adapt, or throw an exception if a grouped use statement is detected (until we got a clean fix). A silent failure is not acceptable though.

**Comment by lisachenko** [comment]
Grouped use statements won't be detected by PhpStorm Annotations plugin also. I really hate this ugly syntax :(

**Comment by yourwebmaker** [comment]
> A silent failure is not acceptable though.

@Ocramius is there an issue/pr regarding this?. If not, @blowski could you create one?

Thanks.

**Comment by blowski** [comment]
@lisachenko The newly released PHPStorm does allow for grouped use statements:

> Support for group use statements
> 
> Enjoy full support for group use statements in PhpStorm, which includes:
> 
> Reuse of group use statements during auto-import
> Support of group uses during refactoring (move method, class, namespaces refactorings)
> Handy intentions to group or split use statements

From https://www.jetbrains.com/phpstorm/whatsnew/

**Comment by lisachenko** [comment]
@blowski yes, sure PhpStorm does, but I'm not sure that "Php Annotations" plugin can handle this syntax too.

**Comment by blowski** [comment]
@lisachenko Just checked, and the PHP Annotations plugin supports it.

**Comment by poldridge** [comment]
I submitted a pull request to fix this 3 months ago: https://github.com/doctrine/annotations/pull/69

**Comment by GeeH** [comment]
Stop saying PhpStorm.

**Comment by Ocramius** [comment]
What's wrong with PhpStorm?

**Comment by GeeH** [comment]
Nothing but I get a ping every time someone mentions it.

**Comment by guilhermeblanco** [comment]
@GeeH which word? PhpStorm?

**Comment by guilhermeblanco** [comment]
@poldridge I left comments on https://github.com/doctrine/annotations/pull/69
Nothing wrong with the patch... it's the language that is borked (PHP grammar is broken in consistency, as always) and both your patch and PHP language needs fix.

**Comment by mikeSimonson** [comment]
Fixed in https://github.com/doctrine/annotations/releases/tag/v1.3.0

Thanks to #69
