### ISSUE TITLE
Improve handling of multiline attribute values

### ISSUE THREAD

**Issue by mjanser** [doctrine/annotations#91]
Example docblock:

```php
/**
 * @Test(
 *     description="This is a very long description
 *                  which needs multiple lines"
 * )
 */
```

The description will result in
```
This is a very long description
 *     which needs multiple lines
```

I'd like that `*` and whitespaces are removed from the parsed string. I tried doing this in [DocParser.php#L1017](https://github.com/doctrine/annotations/blob/master/lib/Doctrine/Common/Annotations/DocParser.php#L1017) by replacing the return with this:
```php
return preg_replace('/^[\t ]*\*[\t ]+/m', '', $this->lexer->token['value']);
```

It works but I'm not sure if that has any side effects or is the right place to do it.

**Comment by Ocramius** [comment]
The behavior as it currently stands is correct. Did the entire whitespace really get collapsed into a ` * ` (space-star-space), or are the newline and the actual spaces still there?

**Comment by Ocramius** [comment]
That is expected behavior... Can't change it without causing a BC break

**Comment by marcioAlmada** [comment]
Is it really expected to have `*` on the parsed arguments? I don't think anyone would want/need this behavior.

@Ocramius how likely it is to have this behavior changed on a next major version?

**Comment by Ocramius** [comment]
> Is it really expected to have `*` on the parsed arguments? I don't think anyone would want/need this behavior.

Yes, it's expected for multi-line strings. Behaves much like NOWDOC syntax.

 > how likely it is to have this behavior changed on a next major version?

Unlikely, but it could be done if a migration tool is provided. See #75 if interested

**Comment by marcioAlmada** [comment]
Ok it seems #75 is a major rewrite, so it's worth taking a look. Thanks!
