### ISSUE TITLE
FileCacheReader putting contents in a tempfile before being allowed to write to it

### ISSUE THREAD

**Issue by func0der** [doctrine/annotations#93]
Hey there,

we have a little problem with the https://github.com/doctrine/annotations/blob/master/lib/Doctrine/Common/Annotations/FileCacheReader.php.

In its [saveCacheFile](https://github.com/doctrine/annotations/blob/master/lib/Doctrine/Common/Annotations/FileCacheReader.php#L205) method it creates a temporary and tries to write to it before setting its permission.

This is a usually not a big problem, because the created file belongs automatically to the creator in a normal filesystem.
BUT if the location where the cache is saved is a location that is a shared storage for example in a virtual machine or maybe a network storage (which is pretty similar) the user is automatically changed.

What is the reason for this seemingly inverted behavior of trying to write before actually having permission to do so for sure?

**Comment by mikeSimonson** [comment]
Can you confirm that assigning rights before the file is created works ? Or the rights are just ignored at the file creation.
