### ISSUE TITLE
System parameters cannot be used as requirements on a QueryParam annotation

### ISSUE THREAD

**Issue by aaronahearne** [doctrine/annotations#95]
The following code does not work when a 'my_regex' parameter is listed in the parameters.yml file. Stepping through the code, this seems to be because the code sees this as class Fos\RestBundle\Validator\Constraints\Regex, which does not implement the ResolvableConstraintInterface. This happens even when my_regex is set to a simple string like 'test'

`* @QueryParam(name="departureTime", requirements="%my_regex%", strict=true, nullable=false)`

**Comment by Ocramius** [comment]
`ResolvableConstraintInterface` is a https://github.com/FriendsOfSymfony/FOSRestBundle concept, not an annotations one - is the annotation read correctly? If so, then this bug is to be moved to that other package.

**Comment by aaronahearne** [comment]
Ah, yeah this should be in the FOSRestBundle, sorry. Should I move it manually?

**Comment by webimpress** [comment]
@aaronahearne yes, please. There is no other possibility. Thanks!
